return {
  ["workshop-1079538195"]={
    ["configuration_options"]={
      ["beebox"]=true,
      ["birdcage"]=true,
      ["cartographydesk"]=true,
      ["cookpot"]=true,
      ["dragonflychest"]=true,
      ["dragonflyfurnace"]=true,
      ["endtable"]=true,
      ["firesuppressor"]=true,
      ["icebox"]=true,
      ["lightning_rod"]=true,
      ["meatrack"]=true,
      ["modsupport"]=false,
      ["moondial"]=true,
      ["mushroom_farm"]=true,
      ["mushroom_light"]=true,
      ["nightlight"]=true,
      ["perdshrine"]=true,
      ["pottedfern"]=true,
      ["rainometer"]=true,
      ["researchlab"]=true,
      ["researchlab2"]=true,
      ["researchlab3"]=true,
      ["researchlab4"]=true,
      ["resurrectionstatue"]=true,
      ["saltlick"]=true,
      ["scarecrow"]=true,
      ["sculptingtable"]=true,
      ["succulent_potted"]=true,
      ["townportal"]=true,
      ["treasurechest"]=true,
      ["wardrobe"]=true,
      ["winterometer"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-1207269058"]={ ["configuration_options"]={  }, ["enabled"]=true },
  ["workshop-1418746242"]={
    ["configuration_options"]={ ["clearfont"]=true, ["eventplus"]=true, ["extratrans"]=true },
    ["enabled"]=true 
  },
  ["workshop-2078243581"]={
    ["configuration_options"]={
      ["Blue"]=0,
      ["Display"]="target",
      ["Green"]=0,
      ["Projectile"]=true,
      ["Red"]=1,
      ["Type"]="hit" 
    },
    ["enabled"]=true 
  },
  ["workshop-2321974509"]={ ["configuration_options"]={ ["SIB"]=false, ["SSB"]=false }, ["enabled"]=true },
  ["workshop-2464402864"]={
    ["configuration_options"]={
      ["Key"]=0,
      ["Others"]=0,
      ["Recipe"]=0,
      ["Stats"]=0,
      ["burn"]=true,
      ["burst"]="KEY_X",
      ["charge"]="KEY_R",
      er=1,
      hp=150,
      ["lang"]=0,
      ["light"]=true,
      ["skill"]="KEY_Z",
      ["stella"]=true,
      ["work"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-2571294157"]={
    ["configuration_options"]={
      ["Key"]=0,
      ["Recipe"]=0,
      ["Stats"]=0,
      ["aiming"]="KEY_R",
      ["burst"]="KEY_X",
      ["charge"]="KEY_F",
      er=1,
      hp=140,
      ["lang"]=0,
      ["skill"]="KEY_Z",
      ["stella"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-2606274649"]={
    ["configuration_options"]={
      ["Key"]=0,
      ["Recipe"]=0,
      ["Stats"]=0,
      ["burst"]="KEY_X",
      er=1.5,
      hp=170,
      ["lang"]=0,
      ["skill"]="KEY_Z",
      ["stella"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-2797919119"]={
    ["configuration_options"]={
      ["Key"]=0,
      ["Recipe"]=0,
      ["Stats"]=0,
      ["burst"]="KEY_X",
      ["charge"]="KEY_R",
      er=1,
      hp=220,
      ["lang"]=0,
      ["skill"]="KEY_Z",
      ["stella"]=true 
    },
    ["enabled"]=true 
  },
  ["workshop-374550642"]={ ["configuration_options"]={ ["MAXSTACKSIZE"]=99 }, ["enabled"]=true },
  ["workshop-378160973"]={
    ["configuration_options"]={
      ["ENABLEPINGS"]=true,
      ["FIREOPTIONS"]=2,
      ["OVERRIDEMODE"]=false,
      ["SHAREMINIMAPPROGRESS"]=true,
      ["SHOWFIREICONS"]=true,
      ["SHOWPLAYERICONS"]=true,
      ["SHOWPLAYERSOPTIONS"]=2 
    },
    ["enabled"]=true 
  } 
}