local str = {
	["STRINGS.NAMES.ONION"] = "洋葱",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.ONION"] = "一个圆而辛辣的根。",
	["STRINGS.NAMES.ONION_COOKED"] = "洋葱圈",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.ONION_COOKED"] = "如果喜欢它，你本应放个洋葱圈在上面。",
	["STRINGS.NAMES.ONION_SEEDS"] = "尖尖的种子",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.ONION_SEEDS"] = "一把怪异的种子。",
	["STRINGS.NAMES.POTATO"] = "土豆",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.POTATO"] = "一个耐寒而富含淀粉的块茎。",
	["STRINGS.NAMES.POTATO_COOKED"] = "烤土豆",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.POTATO_COOKED"] = "一个烤得恰到好处的土豆。",
	["STRINGS.NAMES.POTATO_SEEDS"] = "毛茸茸的种子",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEACHLING"] = "一把怪异的种子。",
	["STRINGS.NAMES.TURNIP"] = "甜菜",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURNIP"] = "一种普通而古老的根类蔬菜。",
	["STRINGS.NAMES.TURNIP_COOKED"] = "熟甜菜",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURNIP_COOKED"] = "依然非常普通。",
	["STRINGS.NAMES.TURNIP_SEEDS"] = "圆圆的种子",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURNIP_SEEDS"] = "一把怪异的种子。",
	["STRINGS.NAMES.GARLIC"] = "大蒜",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARLIC"] = "一种气味强烈却很好吃的根。",
	["STRINGS.NAMES.GARLIC_COOKED"] = "熟大蒜",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARLIC_COOKED"] = "气味变得更大了。",

	["STRINGS.NAMES.GARLIC_SEEDS"] = "豆荚",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARLIC_SEEDS"] = "一把怪异的种子。",

	["STRINGS.NAMES.TOMATO"] = "番茄",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMATO"] = "番茄西红柿。",

	["STRINGS.NAMES.TOMATO_COOKED"] = "熟番茄",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMATO_COOKED"] = "做得恰到好处的番茄。",

	["STRINGS.NAMES.TOMATO_SEEDS"] = "多刺的种子",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMATO_SEEDS"] = "一把怪异的种子。",

	["STRINGS.NAMES.WHEAT"] = "小麦",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHEAT"] = "最好把它磨成面粉。",

	["STRINGS.NAMES.WHEAT_COOKED"] = "熟小麦",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHEAT_COOKED"] = "烤得恰到好处的麦粒。",

	["STRINGS.NAMES.WHEAT_SEEDS"] = "蓝色的种子",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHEAT_SEEDS"] = "一把怪异的种子。",
	
	["STRINGS.NAMES.HOE"] = "锄头",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOE"] = "一把很有用的农具。",
	["STRINGS.RECIPE_DESC.HOE"] = "去挖些土吧。",
	
	["STRINGS.NAMES.VEG_GARDEN_USEABLE"] = "蔬菜园",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.VEG_GARDEN_USEABLE"] = "一个美丽的小园子。",
	["STRINGS.RECIPE_DESC.VEG_GARDEN_USEABLE"] = "一个美丽的小园子。",

	["STRINGS.NAMES.SOIL"] = "可耕作的土壤",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOIL"] = "这块地土很松。",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOIL_FERTILE"] = "这里的土壤很肥沃。",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOIL_TILLED"] = "可以播种了。",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOIL_INFERTILE"] = "我觉得它需要些肥料。",
	
	["STRINGS.NAMES.FLOUR"] = "面粉",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLOUR"] = "一袋面粉。",

	["STRINGS.NAMES.NEWPLANTS"] = "植物",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.NEWPLANTS"] = "一棵美丽的植物。",
	
	["STRINGS.NAMES.SEED_PACKET"] = "袋装种子",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEED_PACKET"] = "一些混合种子。",
	["STRINGS.RECIPE_DESC.SEED_PACKET"] = "都是新种子！",
	
	["STRINGS.NAMES.MEALINGSTONE"] = "磨石",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEALINGSTONE"] = "一块可以磨碎食物的石头。",
	["STRINGS.RECIPE_DESC.MEALINGSTONE"] = "把它们全部磨碎！",
	
	["STRINGS.NAMES.BREAD"] = "面包",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.BREAD"] = "一条面包。",

	["STRINGS.NAMES.CANDIED_POTATO"] = "糖渍土豆",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.CANDIED_POTATO"] = "一个甜甜的土豆。",
	
	["STRINGS.NAMES.MEAT_CAKE"] = "肉蛋糕",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEAT_CAKE"] = "一个用肉做成的蛋糕。",

	["STRINGS.NAMES.POM_PUFF"] = "石榴泡芙",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.POM_PUFF"] = "一种甜滋滋的红色甜点。",
	
	["STRINGS.NAMES.STEW"] = "炖肉",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.STEW"] = "一锅丰盛的炖肉。",

	["STRINGS.NAMES.TOMATO_SOUP"] = "番茄浓汤",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOMATO_SOUP"] = "一道深红色的菜。",
	
	["STRINGS.NAMES.TURNIP_SOUP"] = "甜菜汤",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURNIP_SOUP"] = "一碗甜而鲜亮的汤。",
	
	["STRINGS.NAMES.TURNIP_SUGAR"] = "甜菜糖",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURNIP_SUGAR"] = "一袋磨得很细的甜菜糖。",
	
	["STRINGS.NAMES.MUSHROOMSTUMP"] = "蘑菇树桩",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOMSTUMP"] = "一个腐烂的树桩。",

	["STRINGS.NAMES.FOREST_MUSHROOMS"] = "森林蘑菇",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.FOREST_MUSHROOMS"] = "森林中的菌类。",

	["STRINGS.NAMES.FOREST_MUSHROOMS_COOKED"] = "熟森林蘑菇",
	["STRINGS.CHARACTERS.GENERIC.DESCRIBE.FOREST_MUSHROOMS_COOKED"] = "美味。",
	
	["STRINGS.ACTIONS.MOREPLANT"] = "种植",
	["STRINGS.ACTIONS.HOE"] = "耕种",
	["STRINGS.ACTIONS.MEAL"] = "研磨",
}

AppendStrings(str)

local honey={}
honey.SetNumSlots=function() end
local containers = require("containers")
containers.widgetsetup(honey, "mealingstone")
if honey.widget and honey.widget.buttoninfo then
	honey.widget.buttoninfo.text = "研磨"
end